### ISSUE TITLE
add offline file names to the main script

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/unhcr-popstats#1]
commented out, of course.

**Comment by davidmegginson** [comment]
The filenames are already in the resource objects (or should be). Were they not showing up in CKAN? I might have made a typo.

**Comment by teodorescuserban** [comment]
I was merely add in the commented offline version (following the readme and
trying to make it easier for users).
:)

În Mie, 14 oct. 2015 la 16:35, David Megginson notifications@github.com a
scris:
